FROM rabbitmq:alpine

USER root
WORKDIR /root

ENV PUID ${PUID:-1100}
ENV PGID ${PGID:-1101}
RUN addgroup -S -g ${PGID} plexsync
RUN adduser -S -G plexsync -u ${PUID} plexsync
RUN adduser -S -G plexsync -u ${CELERY_USERID:-912} celery
RUN mkdir /downloads && chown -R plexsync:plexsync /downloads && chmod -R 770 /downloads
VOLUME /downloads

RUN echo "------------------------------------- \
GID/UID \
------------------------------------- \
User uid:    $(id -u plexsync) \
User gid:    $(id -g plexsync) \
------------------------------------- \ " >> /etc/motd
ENTRYPOINT ["supervisord"]

# Expose the Flask port
EXPOSE 5000

#RUN mkdir /downloads && chmod ugo+wx /downloads #&& chown -R plexsync:plexsync /downloads
VOLUME /downloads
VOLUME /config

WORKDIR /app

RUN apk update && apk add nodejs redis supervisor python3 git
RUN npm install -g browserify 
RUN npm install notifyjs
RUN pip3 install --upgrade pip --no-cache-dir

COPY requirements.txt.dev .
RUN pip3 install -r requirements.txt.dev --no-cache-dir

COPY config/supervisord.conf /etc/
COPY  config/config.ini /config/


COPY /templates ./templates
COPY /static  ./static

RUN browserify -d ./static/scripts/main.js > ./static/scripts/bundle.js
#RUN chown -R  plexsync:plexsync /app


COPY app.py .
COPY /plexsync/ ./plexsync

RUN pip3 install -e ./plexsync
