FROM rabbitmq:alpine

WORKDIR /app

# Expose the Flask port
EXPOSE 5000

VOLUME /config
VOLUME /downloads

RUN apk update && apk add nodejs redis supervisor python3 git
RUN npm install -g browserify notifyjs
RUN npm link notifyjs
RUN pip3 install --upgrade pip

COPY requirements.txt.dev .
RUN pip3 install -r requirements.txt.dev 

COPY config/supervisord.conf /etc/
#COPY config/config.ini /config/

ENTRYPOINT ["supervisord"]

COPY /templates ./templates
COPY /static  ./static

RUN browserify -d ./static/scripts/main.js > ./static/scripts/bundle.js

COPY app.py .
COPY /plexsync/ ./plexsync

RUN pip3 install -e ./plexsync




