FROM rabbitmq:alpine

USER root
WORKDIR /root
RUN cd /root

RUN addgroup -g ${GROUPID:-911} -S plexsync
RUN adduser -S -G plexsync -u ${USERID:-911} plexsync

RUN PUID=${PUID:-911}
RUN PGID=${PGID:-911}

RUN echo "------------------------------------- \
GID/UID \
------------------------------------- \
User uid:    $(id -u plexsync) \
User gid:    $(id -g plexsync) \
------------------------------------- \ " >> /etc/motd
ENTRYPOINT ["supervisord"]

# Expose the Flask port
EXPOSE 5000

VOLUME /config
VOLUME /downloads

WORKDIR /app

RUN apk update && apk add nodejs redis supervisor python3 git
RUN npm install -g browserify 
RUN npm install notifyjs
RUN pip3 install --upgrade pip

COPY requirements.txt.dev .
RUN pip3 install -r requirements.txt.dev 

COPY config/supervisord.conf /etc/
COPY  config/config.ini /config/


COPY /templates ./templates
COPY /static  ./static

RUN browserify -d ./static/scripts/main.js > ./static/scripts/bundle.js

COPY app.py .
COPY /plexsync/ ./plexsync

RUN pip3 install -e ./plexsync





